apiVersion: v2
name: grafana
version: 1.0.0
description: Umbrella chart for Grafana
type: application

keywords:
  - grafana
  - monitoring
  - observability

dependencies:
  - name: k8s-monitoring
    version: 3.8.0
    repository: "https://grafana.github.io/helm-charts"
    alias: k8s-monitoring
